qa:
  jsonplaceholder:  "http://jsonplaceholder.typicode.com"
  walmart:  "http://www.walmart.com.br"

prod:
  jsonplaceholder:  "http://jsonplaceholder.typicode.com"
  walmart:  "http://www.walmart.com.br"